server:
  port: 4000

spring:
  application:
    name: badhtaxfileserv
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/taxrefund?currentSchema=taxfileservdb}
    username: ${POSTGRES_USER:taxrefund_user}
    password: ${POSTGRES_PASSWORD:taxrefund_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${FLYWAY_SCHEMAS:taxfileservdb}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  flyway:
    enabled: true
    schemas: taxfileservdb
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration
  
  cloud:
    gcp:
      project-id: ${GOOGLE_CLOUD_PROJECT:}
      credentials:
        location: ${GOOGLE_APPLICATION_CREDENTIALS:}
      pubsub:
        enabled: ${PUBSUB_ENABLED:false}
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      connect-timeout: 2000ms
      read-timeout: 2000ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.badhtaxfileserv: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

pubsub:
  enabled: ${PUBSUB_ENABLED:false}
  refund-update-topic: ${PUBSUB_REFUND_UPDATE_TOPIC:refund-update-from-irs}
  send-refund-topic: ${PUBSUB_SEND_REFUND_TOPIC:send-refund-to-irs}

cache:
  type: ${CACHE_TYPE:redis}
  redis:
    time-to-live: 3600000  # 1 hour in milliseconds
    cache-null-values: false

redis:
  enabled: ${REDIS_ENABLED:true}

